name          'puppet-rsyslog'
version       '0.1.0'
source        'https://github.com/chriscowley/puppet-rsyslog'
author        'Chris Cowley'
license       'Apache License, Version 2.0'
summary       'Rsyslog module'
description   'Installs and configures rsyslog'
project_page  'https://github.com/chriscowley/puppet-rsyslog'

dependency 'puppetlabs/stdlib'
